#BUtils.jl
#This is where the magnetic calculation models and utlities reside
export biotSavart,B,lorentzForce

#mu0=mu/(4pi), mu is the magnetic permitivity
mu0=(1/10^7)
#The biotSavart function is the function that implements the Integrand of the Biot-Savart Law from E&M. This law yields the magnetic field at a point r in 3D space given a point current of magnitude I.
#Parameters:
#coil: Coil type object (located in CSIM.jl)
#theta: Parameter of coil, IE where along the coil we should place the point current
#r: Field Point at which we are measuring the magnetic field generated, it is given as a vector
#A few things to note about this method
#1. This biotSavart law does not include the dTheta term in dl because that is supplied by quadgk in the B Calculator below, since it does not make any sense to compute the magnetic field due to a point current
#2. This integrand also does not include the magnetic permitivity, this is because the integrand does not need it.
function biotSavart(coil::Coil,theta::Number,r)
  dl=coil.df(theta)
  dr=r-coil.f(theta)
  ldr=sqrt(dr[1]^2+dr[2]^2+dr[3]^2)
  f=coil.I*cross(dl,dr)/ldr^3
  return f
end

#Calculates the magnetic field due a coil with constant current I flowing through it, at field point r
#Parameters:
#Coil, the geometry of the coil involved
#r, vector (list with 3 elements) representing the field point at which the magnetic field generated by current flowing through are coil is measured
function B(coil::Coil,r)
  BF=quadgk(theta -> biotSavart(coil,theta,r),coil.xMin,coil.xMax)
  return mu0*BF[1]
end

#Calculates the magnetic field due an assembly, but not including the magnetic field from the mobile coil since we wish to compute forces on the mobile coil
#Coil, the geometry of the coil involved
#r, vector (list with 3 elements) representing the field point at which the magnetic field generated by current flowing through are coil is measured
function B(asb::Assembly,r)
  netB=B(asb.coils[1],r)
  for tcoils=asb.coils[2:]
  	netB=netB+B(tcoils,r)
  end
  return netB
end

#Implemented the lorentzForce law where each of the coils coil1 and coil2 are both energized with currents I1 and I2 respectively.
#Parameters:
#coil1,coil2: Coils which are correctly translated into position in 3D space
function lorentzForce(I1::Number,I2::Number,coil1::Coil,coil2::Coil)
  return quadgk(theta->cross(coil1.I*coil2.df(theta),B(coil1,f2(theta))[1]),coil2.xMin,coil2.xMax)
end